import Link from "next/link";
import ProjectShowcase from "@/components/ProjectShowcase";
import ProjectScreenshot from "@/components/ProjectScreenshot";
import EditorialPage from "@/components/EditorialPage";
import DirectionArrow from "@/components/DirectionArrow";
import { pageMetadata, JsonLd, absoluteUrl } from "@/lib/seo";
import s from "@/components/editorial.module.css";
import d from "@/components/project-details.module.css";

export const metadata = pageMetadata("Rümpelross: Webdesign für Entrümpelung | leoquent", "Einblicke in das Website-Projekt für Rümpelross: weiterentwickelte Gestaltung, eigene Icons und Animationen, Anfrage-Quiz und Foto-Schnellangebot per WhatsApp.", "/referenzen/ruempelross/");

export default function RuempelrossCaseStudy() {
  return <EditorialPage label="Rümpelross" project="yellow">
    <JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [
      { "@type": "ListItem", position: 1, name: "Start", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "Webdesign", item: absoluteUrl("/webdesign/") },
      { "@type": "ListItem", position: 3, name: "Rümpelross", item: absoluteUrl("/referenzen/ruempelross/") },
    ] }} />
    <div className={d.hero}><p className={s.eyebrow}>Aus meiner Arbeit / Rümpelross</p><h1>Platz schaffen.<br /><span>Schon beim ersten Klick.</span></h1><p className={d.intro}>Eine Marke mit Charakter. Eine Website, die den Weg zur Anfrage erleichtert.</p></div>
    <ProjectShowcase name="Rümpelross" poster="/referenzen/ruempelross-desktop.webp" mobile="/referenzen/ruempelross-mobile.webp" color="#c9a600" />
    <div className={d.overview}><p>Ein Ross mit Charakter, ein Angebot mit vielen Facetten. Für Rümpelross habe ich den bestehenden Markenauftritt weiterentwickelt und in eine Website übersetzt: mit eigenen Texten, Icons und Animationen. Ein Anfrage-Quiz und ein Foto-Schnellangebot per WhatsApp helfen Besuchern, ihr Vorhaben zu beschreiben.</p><p>Markengestaltung · Text · Webdesign · Animation · Entwicklung<br />Einblicke in den Website-Projektstand</p></div>
    <dl className={s.facts}><div><dt>Unternehmen</dt><dd>Rümpelross<br />Entrümpelung in Stuttgart</dd></div><div><dt>Der Ausgangspunkt</dt><dd>Eine Marke mit Comic-Charakter und ein breites Angebot rund um Räumung und Haushaltsauflösung</dd></div><div><dt>Die Aufgabe</dt><dd>Den Charakter erhalten, Vertrauen vermitteln und Anfragen für das Erstgespräch vorbereiten</dd></div></dl>
    <section className={s.section}><h2>Der Charakter bleibt.<br />Der Auftritt wächst.</h2><div><p>Das Ross gibt der Marke ihren unverwechselbaren, comichaften Charakter. Den habe ich beibehalten und die Gestaltung darum seriöser und moderner aufgebaut. Gelb und Schwarz bleiben prägend. Klare Typografie, helle Informationsflächen und eine geordnete Seitenstruktur geben den Inhalten Ruhe.</p><p>Das vorhandene Logo habe ich vektorisiert. Dazu entstanden eigens gestaltete Icons für die Website. Sie greifen den Charakter der Marke auf und helfen, Leistungen und Abläufe schnell zu erfassen.</p><p>„Wenn viel zu viel wird, packen wir an.“ Die Einstiegszeile spricht die Situation der Besucher direkt an. Ein Drohnenflug über Stuttgart stellt den regionalen Bezug her und gibt der Website einen bewegten Auftakt.</p></div></section>
    <ProjectScreenshot src="/referenzen/ruempelross-leistungen.webp" width={1250} height={791} alt="Rümpelross: sechs illustrierte Leistungen auf einer hellen Fläche mit gelber Navigation">Individuell gestaltete Icons machen die Leistungen unterscheidbar. Die helle Fläche schafft einen ruhigen Gegenpol zum dunklen Einstieg.</ProjectScreenshot>
    <section className={s.section}><h2>Die passende Hilfe.<br />Schnell erkennbar.</h2><div><p>Entrümpelung, Haushaltsauflösung oder einzelne Rückbauarbeiten: Die Leistungsübersicht macht unterschiedliche Anliegen sichtbar. Eigene Leistungsseiten erklären die Details und sind in Inhalt und Aufbau auf die Suche nach diesen Leistungen abgestimmt.</p><p>Ein Ablauf in vier Schritten erklärt den Weg von der ersten Anfrage bis zur Übergabe. Für diese Erzählung habe ich das Ross animiert und in den Scrollverlauf eingebaut. So begleitet das Maskottchen die Besucher durch den Ablauf.</p><p>Vorher-Nachher-Ansichten zeigen die Veränderung am Objekt. Besucher können dadurch besser einordnen, welche Arbeit hinter dem Angebot steckt.</p></div></section>
    <ProjectScreenshot src="/referenzen/ruempelross-kontakt.webp" width={1250} height={791} alt="Beispielhafter WhatsApp-Dialog neben einer Erklärung zur Anfrage mit Fotos">Ein dargestellter Beispieldialog erklärt die Anfrage mit Fotos. Er veranschaulicht den Ablauf und zeigt keine echte Kundennachricht.</ProjectScreenshot>
    <section className={s.section}><h2>Aus Interesse wird<br />eine konkrete Anfrage.</h2><div><article><h3>Das Erstgespräch vorbereiten.</h3><p>Ein eigens entwickeltes Quiz führt durch sechs Fragen zum Vorhaben. Es erfasst unter anderem Objektart, Größe, Füllgrad, Zugang und Wunschtermin. Die Angaben werden übersichtlich zusammengefasst. So lassen sich Anfragen vorab einordnen und das erste Gespräch beginnt mit einem klareren Bild der Aufgabe.</p></article><article><h3>Anfragen auf eigener Infrastruktur.</h3><p>Die Verarbeitung der Quiz-Anfragen läuft über einen eigenen Server-Endpunkt auf meiner Infrastruktur. Ich kümmere mich damit auch um die Technik hinter dem Anfrageweg – mit einem Ansprechpartner für Website, Quiz und Betrieb.</p></article><article><h3>Mit Fotos zum Schnellangebot.</h3><p>Als zweiten Anfrageweg habe ich das Foto-Schnellangebot per WhatsApp umgesetzt. Eine eigens erstellte Chat-Animation zeigt, wie es funktioniert: Fotos aufnehmen, senden und Rückmeldung erhalten. Der Beispieldialog macht den Ablauf sichtbar, bevor Besucher selbst Kontakt aufnehmen.</p></article><article><h3>Auf dem Handy erreichbar bleiben.</h3><p>Die mobile Darstellung ordnet Inhalte untereinander und hält die Kontaktwege griffbereit. Telefonnummer und Anfrage sind auch dann erreichbar, wenn Besucher bereits tiefer in die Leistungen eingestiegen sind.</p></article></div></section>
    <div className={d.related}><Link href="/referenzen/gebrueder-ross/"><span><small>Weiteres Projekt</small>Gebrüder Ross</span><DirectionArrow diagonal /></Link></div>
    <div className={s.callout}><h2>Ein Auftritt,<br />der zu Ihrer Arbeit passt.</h2><p>Ich bringe Angebot, Texte und Gestaltung zusammen. Damit Ihre Besucher verstehen, was Sie für sie tun können.</p><Link href="/webdesign/#kontakt" className={s.button}>Über Ihre Website sprechen <DirectionArrow diagonal /></Link></div>
  </EditorialPage>;
}
