import Link from "next/link";
import EditorialPage from "@/components/EditorialPage";
import DirectionArrow from "@/components/DirectionArrow";
import { pageMetadata, JsonLd, absoluteUrl } from "@/lib/seo";
import s from "@/components/editorial.module.css";

const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
const title = "SEO & KI-Suche: Inhalte mit Substanz | Leoquent";
const description = "Wie ich Websites für Google und KI-Suche plane: klare Leistungsseiten, eigene Texte, belegbare Erfahrung und eine technisch zugängliche Website.";
export const metadata = pageMetadata(title, description, "/webdesign/seo-und-ki-suche/");

export default function SearchPage() {
  return <EditorialPage label="SEO & KI-Suche">
    <JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: "Gefunden werden beginnt mit verstanden werden.", description, author: { "@id": absoluteUrl("/#leonid") }, publisher: { "@id": absoluteUrl("/#organization") }, mainEntityOfPage: absoluteUrl("/webdesign/seo-und-ki-suche/"), datePublished: "2026-09-30", dateModified: "2026-09-30", inLanguage: "de-DE", image: absoluteUrl("/og-image-1200x630.png") }} />
    <div className={s.hero}><p className={s.eyebrow}>Webdesign / Suchmaschinen und KI-Suche</p><h1>Gefunden werden beginnt<br /><span>mit verstanden werden.</span></h1><p className={s.lead}>Was bieten Sie an? Für wen ist es gedacht? Und warum sollte man Ihnen vertrauen? Ich entwickle Inhalte, die diese Fragen konkret beantworten – und mache sie für Suchmaschinen zugänglich.</p><div className={s.author}><img src={base + "/FOTOS/leonid_cropped_2.webp"} alt="Leonid Ryazanskiy" width="65" height="65" /><span>Von Leonid Ryazanskiy · Leoquent<br />Stand: 30. September 2026</span></div></div>
    <section className={s.section}><h2>Was SEO und GEO<br />für Ihre Website bedeuten.</h2><div><p>SEO umfasst die Arbeit daran, dass Suchmaschinen Inhalte finden, verstehen und passend zu einer Suche anzeigen können. GEO steht für Generative Engine Optimization und bezeichnet die Optimierung für Antworten in KI-Suchdiensten.</p><p>Für Googles KI-Funktionen gelten die bestehenden SEO-Grundlagen. Google verlangt dafür weder spezielle KI-Dateien noch ein eigenes Markup. Eine klare Website mit hilfreichen Inhalten bleibt der Ausgangspunkt. <a href="https://developers.google.com/search/docs/appearance/ai-features">Quelle: Google Search Central</a>.</p><p>Eine Platzierung oder Erwähnung lässt sich nicht garantieren. Mein Beitrag ist eine belastbare Grundlage: verständliche Inhalte, nachvollziehbare Aussagen und eine technisch sauber zugängliche Seite.</p></div></section>
    <section className={s.section}><h2>Was ich konkret<br />für Ihren Auftritt tue.</h2><div><article><h3>Fragen vor Suchbegriffe stellen.</h3><p>Ich kläre, was Ihre Kunden vor einer Anfrage wissen müssen: Leistungen, Ablauf, Voraussetzungen, Kostenrahmen und Grenzen. Daraus entstehen Texte mit einer klaren Antwort und passenden Details. Suchbegriffsrecherche ergänzt diese Arbeit je nach vereinbartem Umfang.</p></article><article><h3>Jeder wichtigen Seite eine Aufgabe geben.</h3><p>Eine Leistungsseite erklärt ein bestimmtes Angebot. Ein Projekt zeigt die Umsetzung. Eine persönliche Vorstellung erklärt Erfahrung und Arbeitsweise. Seitentitel, Überschriften und interne Links machen diese Zusammenhänge deutlich.</p></article><article><h3>Eigene Erfahrung belegen.</h3><p>Konkrete Projekte, nachvollziehbare Entscheidungen, eigene Bilder und freigegebene Kundenstimmen machen Aussagen prüfbar. Bei Leoquent zeigt das beispielsweise die <Link href="/referenzen/gebrueder-ross/">Projektseite zu Gebrüder Ross</Link>.</p></article><article><h3>Die technische Grundlage sichern.</h3><p>Wichtige Informationen stehen als lesbarer Text auf der Seite. Dazu kommen passende Metadaten, eindeutige Seitenadressen, eine Sitemap und strukturierte Daten, die zum sichtbaren Inhalt passen. Mobile Bedienung und angemessene Bildgrößen gehören ebenfalls dazu.</p></article></div></section>
    <section className={s.section}><h2>Eine Seite oder mehrere?<br />Das Angebot entscheidet.</h2><div><p>Für ein überschaubares Angebot kann eine einzelne Seite ausreichen. Eigene Unterseiten sind sinnvoll, wenn unterschiedliche Anliegen eine eigenständige Antwort brauchen.</p><p>Ein Beispiel: Auf der Hauptseite eines Nachlassdienstleisters reicht zunächst der Überblick. Wer konkret nach Objektbegehung oder Nachlassverwertung sucht, braucht mehr Details zu diesem Ablauf. Deshalb gibt es beim <Link href="/referenzen/gebrueder-ross/">Auftritt von Gebrüder Ross</Link> vertiefende Leistungsseiten.</p><p>Für Ihre Website plane ich die Seitenzahl nach den Fragen Ihrer Kunden und den vorhandenen Inhalten. Jede Seite soll etwas Eigenes beitragen.</p></div></section>
    <section className={s.section}><h2>Was zum Projekt gehört.<br />Und was danach folgt.</h2><div><p>Technische SEO-Grundlagen gehören zu jedem meiner Website-Pakete. Im Paket Auftritt kommen Suchbegriffsrecherche und darauf abgestimmte Inhalte hinzu. Wachstum bietet Raum für eine erweiterte Suchstrategie und gezielte Leistungsseiten.</p><p>Nach dem Start zeigen tatsächliche Suchanfragen und Anfragen von Kunden, wo Inhalte fehlen oder unklar bleiben. Diese Auswertung und Weiterentwicklung kann Teil einer vereinbarten laufenden Betreuung sein.</p><Link href="/webdesign/#preise">Website-Pakete und Betreuung ansehen</Link></div></section>
    <section className={s.section}><h2>Grundlagen<br />zum Nachlesen.</h2><div><ul><li><a href="https://developers.google.com/search/docs/appearance/ai-features">Google: Anforderungen für AI Overviews und AI Mode</a></li><li><a href="https://developers.google.com/search/docs/fundamentals/creating-helpful-content">Google: hilfreiche Inhalte und nachvollziehbare Erfahrung</a></li><li><a href="https://developers.openai.com/api/docs/bots">OpenAI: Suchcrawler und ihre Zugriffsmöglichkeiten</a></li></ul><p>Diese Quellen beschreiben die Grundlagen. Die konkrete Seitenstruktur und die Inhalte entwickle ich aus Ihrem Angebot.</p></div></section>
    <div className={s.callout}><h2>Welche Fragen sollte<br />Ihre Website beantworten?</h2><p>Im Erstgespräch schauen wir auf Ihr Angebot, Ihre Kunden und den bestehenden Auftritt. Daraus lässt sich ein sinnvoller Umfang ableiten.</p><a href="mailto:hi@lqnt.de?subject=Website%20und%20Sichtbarkeit" className={s.button}>Vorhaben besprechen <DirectionArrow diagonal /></a></div>
  </EditorialPage>;
}
