import Link from "next/link";
import ProjectShowcase from "@/components/ProjectShowcase";
import EditorialPage from "@/components/EditorialPage";
import DirectionArrow from "@/components/DirectionArrow";
import { pageMetadata, JsonLd, absoluteUrl } from "@/lib/seo";
import s from "@/components/editorial.module.css";

const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
export const metadata = pageMetadata("Gebrüder Ross: Webdesign für Nachlassservice | Leoquent", "Einblicke in den Website-Auftritt für Gebrüder Ross: ein sensibles Angebot verständlich erklären, Leistungen strukturieren und persönliche Ansprechpartner zeigen.", "/referenzen/gebrueder-ross/");

export default function RossCaseStudy() {
  return <EditorialPage label="Gebrüder Ross">
    <JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [
      { "@type": "ListItem", position: 1, name: "Start", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "Webdesign", item: absoluteUrl("/webdesign/") },
      { "@type": "ListItem", position: 3, name: "Gebrüder Ross", item: absoluteUrl("/referenzen/gebrueder-ross/") }
    ] }} />
    <div className={s.hero}><p className={s.eyebrow}>Aus meiner Arbeit / Gebrüder Ross</p><h1>Vertrauen beginnt<br /><span>mit Klarheit.</span></h1><p className={s.lead}>Ein Website-Auftritt für ein sensibles Thema: Gebrüder Ross übernimmt die operative Arbeit vor Ort – und entlastet damit beispielsweise Nachlasspfleger bei der Abwicklung. Ich habe daraus einen vollständigen digitalen Auftritt entwickelt: von Recherche, Logo und Texten bis zu Website und Betrieb.</p><p className={s.meta}>Recherche · Marke · Text · Design · Entwicklung · Betrieb</p></div>
    <ProjectShowcase name="Gebrüder Ross" domain="gebruederross.de" poster="/referenzen/gebrueder-ross-desktop.webp" video="/referenzen/gebrueder-ross-rundgang.webm" mobile="/referenzen/gebrueder-ross-mobile.webp" />
    <dl className={s.facts}><div><dt>Unternehmen</dt><dd>Gebrüder Ross<br />Nachlassservice</dd></div><div><dt>Adressaten der Website</dt><dd>Nachlasspfleger, Verwalter und weitere professionelle Auftraggeber</dd></div><div><dt>Aufgabe des Auftritts</dt><dd>Leistungen erklären, Vertrauen aufbauen und Kontakt erleichtern</dd></div></dl>
    <section className={s.section}><h2>Ein sensibles Thema.<br />Ein klares Verständnis.</h2><div><p>Bei einem Nachlass geht es um den Besitz und die Geschichte eines verstorbenen Menschen. Auftraggeber müssen sich darauf verlassen können, dass vor Ort sorgfältig und nachvollziehbar gearbeitet wird. Der Auftritt sollte diese Verlässlichkeit vermitteln.</p><p>Am Anfang standen Wettbewerbsanalyse und Zielgruppenrecherche. Daraus entwickelte ich die Inhalte und die klare Rollenverteilung: Während ein Nachlasspfleger beispielsweise die administrativen Aufgaben übernimmt, kümmert sich Gebrüder Ross um die operative Umsetzung am Objekt.</p><p>Die Inhalte wurden mit einem Nachlasspfleger aus Stuttgart fachlich abgestimmt.</p></div></section>
    <section className={s.section}><h2>Vertrauen gestalten.<br />Bis ins Detail.</h2><div><article><h3>Blau, Weiß und Gold mit einer Aufgabe.</h3><p>Dunkelblau gibt dem Auftritt Ruhe, helle Flächen schaffen Raum für Informationen und Gold setzt gezielte Akzente. Der Wechsel der Flächen gliedert die Inhalte. Die Gestaltung soll der sensiblen Aufgabe und den professionellen Auftraggebern gerecht werden.</p></article><article><h3>Eine Marke für alle Anwendungen.</h3><p>Zur Arbeit gehörten Logoentwicklung und die saubere Vektorisierung von Signet und Wortmarke. Das Markenpaket enthält Varianten für helle und dunkle Hintergründe, skalierbare SVG-Dateien, transparente PNGs, Favicons und eine eigene Linkvorschau.</p></article><article><h3>Persönliche Bilder für die Zielgruppe.</h3><p>Passende Aufnahmen der beiden Ansprechpartner in Anzügen lagen nicht vor. Ich entwickelte deshalb ein digitales KI-Fotoshooting auf Basis vorhandener Bilder und passte die Bildsprache an die Zielgruppe an. Das auf der Website verwendete Porträt ist KI-gestützt bearbeitet.</p></article></div></section>
    <figure className={s.detailFigure}><img src={base + "/referenzen/gebrueder-ross-team.webp"} width="1280" height="800" loading="lazy" alt="Helle Teamsektion mit der Vorstellung von Simon Bartosch und Raphael Uhland und ihrem KI-gestützt bearbeiteten Porträt" /><figcaption>Persönliche Ansprechpartner auf einer hellen Fläche. Das Porträt wurde mit KI aus vorhandenem Bildmaterial entwickelt.</figcaption></figure>
    <section className={s.section}><h2>Die richtigen Worte.<br />Die passende Tiefe.</h2><div><p>Die gesamte Textentwicklung gehörte zum Projekt: vom ersten Satz über die Leistungsbeschreibungen bis zu den Antworten auf häufige Fragen. Die Texte erklären konkrete Aufgaben, Abläufe und Kontaktmöglichkeiten.</p><p>Die Hauptseite bietet den Überblick. Sechs eigene Leistungsseiten vertiefen wichtige Anliegen wie Nachlassverwertung, Objektbegehung oder Haushaltsauflösung nach einem Todesfall. Zehn häufige Fragen und 19 strukturierte Leistungen ergänzen den Auftritt.</p><p>Auf dem Handy lassen sich Details gezielt öffnen. So bleibt das umfangreiche Angebot überschaubar, ohne wichtige Informationen wegzulassen.</p></div></section>
    <figure className={s.detailFigure}><img src={base + "/referenzen/gebrueder-ross-leistungen.webp"} width="1280" height="800" loading="lazy" alt="Leistungsübersicht von Gebrüder Ross mit gezielt aufklappbaren Beschreibungen" /><figcaption>Ein Überblick als Einstieg, ausführliche Leistungsseiten zur Vertiefung.</figcaption></figure>
    <section className={s.section}><h2>Die Technik dahinter.<br />Der Betrieb danach.</h2><div><article><h3>Für mobile Verbindungen optimiert.</h3><p>Komprimierte Bilder, schlanke Dateien und eine angepasste Zwischenspeicherung reduzieren die zu übertragenden Daten. Die mobile Gestaltung und die technischen Optimierungen wurden gemeinsam entwickelt.</p></article><article><h3>Formularversand in eigener Hand.</h3><p>Für Kontaktanfragen habe ich einen eigenen Server-Endpunkt umgesetzt. Hosting und die serverseitige Verarbeitung liegen auf meiner Infrastruktur in Deutschland. Telefon und E-Mail bleiben als alternative Kontaktwege sichtbar.</p></article><article><h3>Nutzung datensparsam verstehen.</h3><p>Die Besucherstatistik läuft mit selbst gehostetem Umami. Sie verwendet keine Analyse-Cookies und speichert keine IP-Adressen in der Statistik. Suchmaschinen erhalten eine Sitemap sowie strukturierte Angaben zu Unternehmen und Leistungen.</p></article><article><h3>Ein Ansprechpartner für den gesamten Auftritt.</h3><p>Domain-Einrichtung und Hosting übernehme ich ebenfalls. Der Kunde muss dafür keine verschiedenen technischen Anbieter koordinieren. Das Projekt umfasst damit auch die Arbeit, die nach außen kaum sichtbar ist.</p></article><a className={s.button} href="https://gebruederross.de/" target="_blank" rel="noreferrer">Die Website besuchen <DirectionArrow diagonal /></a></div></section>
    <div className={s.callout}><h2>Auch Ihr Angebot<br />verdient einen klaren Auftritt.</h2><p>Ich entwickle Websites, die ein Unternehmen verständlich machen: mit Konzept, eigenen Texten und einer Gestaltung, die dazu passt.</p><Link href="/webdesign/#kontakt" className={s.button}>Über Ihre Website sprechen <DirectionArrow diagonal /></Link></div>
  </EditorialPage>;
}
