export const applications = [
  {
    id: "anfragen",
    label: "Anfragen kommen von überall.",
    category: "Anfragen & Antworten",
    title: "Aus vielen Nachrichten wird ein klarer Vorgang.",
    lead: "E-Mails, Anhänge und Gesprächsnotizen zusammenführen. KI kann das Anliegen einordnen, fehlende Angaben erkennen und den nächsten Schritt vorbereiten.",
    steps: ["Nachrichten & Unterlagen", "Anliegen erkennen & zuordnen", "Vorgang & Antwortentwurf"],
    sample: "Eine neue Anfrage, für Sie aufbereitet",
    result: ["Wunsch, Termin und vorhandene Angaben zusammengefasst", "Fehlende Information als Rückfrage vorbereitet", "Passende Antwort als Entwurf hinterlegt"],
    human: "Sie prüfen die Antwort und geben Zusagen frei.",
  },
  {
    id: "dokumentation",
    label: "Nach dem Termin wartet die Dokumentation.",
    category: "Dokumentation & Nachbereitung",
    title: "Kurz einsprechen. Bericht vorbereitet.",
    lead: "Eine eigene Sprachnotiz nach dem Termin kann zum strukturierten Bericht werden. Erledigte Arbeiten, offene Punkte und nächste Schritte werden zugeordnet.",
    steps: ["Eigene Sprachnotiz", "Inhalte ordnen & strukturieren", "Bericht & Aufgaben"],
    sample: "Aus Ihrer Notiz wird ein Berichtsentwurf",
    result: ["Durchgeführte Arbeiten übersichtlich festgehalten", "Offene Punkte als Aufgaben vorgeschlagen", "Unterlagen dem passenden Auftrag zugeordnet"],
    human: "Sie prüfen die Angaben und geben den Bericht frei.",
  },
  {
    id: "belege",
    label: "Jeder Beleg wird noch abgetippt.",
    category: "Belegerfassung & Datenpflege",
    title: "Beleg fotografieren. Daten übernehmen lassen.",
    lead: "Sie fotografieren einen Materialbeleg. Ein KI-Agent kann Lieferant, Datum, Positionen und Beträge auslesen, einen strukturierten Datensatz anlegen und ihn in die angebundene Anwendung übertragen.",
    steps: ["Foto vom Beleg", "KI liest & ordnet Angaben", "Eintrag im Zielsystem"],
    sample: "Beispiel: Materialeinkauf eines Heizungsbetriebs",
    result: ["Lieferant, Datum, Positionen und Beträge als Datensatz erfasst", "Beleg dem passenden Auftrag zugeordnet", "Angaben nach vereinbarten Prüfregeln in die Anwendung übernommen"],
    human: "Sie prüfen unklare Angaben und geben notwendige Korrekturen frei.",
  },
  {
    id: "wissen",
    label: "Das Wissen ist da. Aber wo?",
    category: "Unternehmenswissen & Suche",
    title: "Fragen stellen. Wissen mit Fundstelle finden.",
    lead: "Ein interner KI-Assistent kann freigegebene Anleitungen, Unterlagen und Vorgänge durchsuchen. Antworten beziehen sich auf das Wissen Ihres Betriebs.",
    steps: ["Frage aus dem Arbeitsalltag", "Passende Unterlagen finden", "Antwort mit Fundstellen"],
    sample: "„Wie gehen wir bei diesem Auftrag vor?“",
    result: ["Passende Arbeitsanweisung auffindbar", "Wichtige Schritte verständlich zusammengefasst", "Verwendete Unterlagen direkt verlinkt"],
    human: "Sie können die Quelle prüfen und entscheiden über die Anwendung.",
  },
  {
    id: "kunden",
    label: "Kundeninfos sind über alles verteilt.",
    category: "Kundenmanagement & Nachverfolgung",
    title: "Die Kundenbeziehung auf einen Blick.",
    lead: "Gesprächsnotizen, E-Mails und Angebote beim passenden Kunden zusammenführen. KI kann Kontakte zuordnen, Gespräche zusammenfassen und nächste Schritte vorbereiten – in Ihrem vorhandenen CRM oder einer eigenen Kundenübersicht.",
    steps: ["Kontakte & Gesprächsnotizen", "Kunden zuordnen & ergänzen", "Kundenverlauf & nächste Schritte"],
    sample: "Vor dem Rückruf ist der aktuelle Stand schon da",
    result: ["Letzter Kontakt, offene Angebote und Zusagen zusammengefasst", "Neue Gesprächsnotizen dem richtigen Kunden zugeordnet", "Erinnerungen und passende Rückfragen vorbereitet"],
    human: "Sie entscheiden über Angebote, Zusagen und den nächsten Kundenkontakt.",
  },
  {
    id: "ueberblick",
    label: "Für den Überblick muss ich überall nachsehen.",
    category: "Übersicht & Steuerung",
    title: "Eine Übersicht, die Zusammenhänge zeigt.",
    lead: "Informationen aus Ihren Anwendungen in einer eigenen Übersicht zusammenführen. Offene Vorgänge bleiben sichtbar; KI kann Rückmeldungen verdichten und Auffälligkeiten erläutern.",
    steps: ["Status & Rückmeldungen", "Informationen zusammenführen", "Übersicht & offene Punkte"],
    sample: "Der Arbeitsstand auf einen Blick",
    result: ["Was noch auf Unterlagen oder Rückmeldung wartet", "Welche Termine und nächsten Schritte anstehen", "Wo sich ein genauerer Blick lohnt"],
    human: "Sie setzen Prioritäten und entscheiden, wo Sie eingreifen.",
  },
];

export type ApplicationExample = typeof applications[number];
